### ISSUE TITLE
patientproblemcode - MDR keys decimal -> int

### ISSUE THREAD

**Issue by jadczak-sibel** [jadczak/mauder#2]
The patientproblemcode.txt format has changed.

The MRD report keys are no longer decimal.  They have been changed to ints..

![image](https://github.com/user-attachments/assets/8b17fa78-1965-4be2-a2c3-2ca30f4a7e5a)

**Comment by jadczak** [comment]
fixed in e67c6a1757820e70c3f0147961f40e9f52bab348
